name: Návrh vylepšení
description: Navrhni zlepšení pro GameHub.
title: "feat: "
labels: [enhancement]
body:
  - type: input
    id: problem
    attributes:
      label: Problém
      description: Jaký uživatelský problém to řeší?
      placeholder: Je složité ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Navrhované řešení
      description: Popiš očekávané chování a UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Zvažované alternativy
  - type: dropdown
    id: impact
    attributes:
      label: Dopad
      options:
        - Vysoký
        - Střední
        - Nízký
    validations:
      required: true
